// GENERATED BY harness/gen_level_param.py — DO NOT EDIT BY HAND.
//
// The LEVEL network (E4G1 = n19/n14) as an EXPLICIT function of the
// knob. Replaces the fixed `kE4G1` of `nls_e234_coef*.h`, valid only
// at lvl=0: with it, turning the volume down cost up to +3,4 dB of
// ANMR.
//
// Q2's base enters as [rpi + (beta+1)*Ze(s)] || Cb: the follower
// describes the LOWS and the junction the HIGHS, and BOTH are needed.
// Fitted at four positions at once — two numbers for the whole
// travel, not a table. Valid because the pot sits BEFORE the base, so
// the load Q2 presents does not depend on the knob.
//
// FIT: rpi = 192.2089 kOhm, Cb = 2.6939 pF (beta = 416,4 from the netlist)
// The verification figure is NOT hand-written here: the run emits
// it, below. The one this line used to carry was from an EARLIER base
// model and sat 55 dB away from what the generator measured.
//
// THIS RUN:  R15 = 100000 Ohm (output load, after C9)  ·  R14 = 470 Ohm  ·  R13 = 10000 Ohm (Q2 emitter, both models)
//   worst signal residual n19/n14 :  -105.7 dB
//   worst rail -> n19 residual    :   -95.1 dB
#pragma once

namespace nlsc {
namespace level_v9ri {

static constexpr double kScale = 6283.1853071795867;
static constexpr int kGradoNum = 3;
static constexpr int kGradoDen = 4;
static constexpr int kKnobDeg = 2;

// [power of s, highest to lowest][lvl^2 ... lvl^0]
static constexpr double kB[4][3] = {
    {+0.00000000000000000e+00, -1.15869099502823997e+09, +1.15869100661514974e+09},
    {+0.00000000000000000e+00, -1.82855331304656778e+05, +1.82855333133210079e+05},
    {+0.00000000000000000e+00, +0.00000000000000000e+00, +0.00000000000000000e+00},
    {+0.00000000000000000e+00, +0.00000000000000000e+00, +0.00000000000000000e+00},
};
static constexpr double kA[5][3] = {
    {-1.96124944278866309e+06, +1.94163694836077630e+06, +1.96125142365061984e+04},
    {-2.52351924506418169e+08, +2.49825283835919440e+08, +1.17283609776914001e+09},
    {-3.94784176043574334e+04, -3.62546928411178640e+05, +6.48734166638722178e+06},
    {+0.00000000000000000e+00, -6.28318530717958623e+01, +7.38060580212308469e+03},
    {+0.00000000000000000e+00, +0.00000000000000000e+00, +1.00000000000000000e+00},
};

// ═══════════════════════════════════════════════════════════════════
//  THE RAIL PATH: v(n19)/v(VR), ALSO a function of the knob.
// ═══════════════════════════════════════════════════════════════════
// This replaces `rail::kN19` of `nls_rail_n3.h`, which was ONE
// FIXED filter measured at lvl=0 — and the transfer changes 58x
// along the pot (0,0128 -> 0,742 at 1 kHz).
// Why it dominated the residual: the rail enters `n19` via `R12`,
// AFTER the pot, so its error does NOT attenuate with the knob. As
// the volume drops the signal falls 4,2x and the error stays => it
// rules.
// From the SAME matrix as `kB`/`kA` with the other right-hand
// side, and the SAME fitted Q2-base model: literally the
// superposition the cascade sums.
static constexpr int kGradoNumR = 3;
static constexpr int kGradoDenR = 4;
static constexpr int kKnobDegR = 2;

static constexpr double kBr[4][3] = {
    {-2.27194312750635266e+08, +1.38361336465136886e+09, +1.38588669593612831e+07},
    {-3.58539865303248589e+04, -1.43240201196617913e+05, +5.85996103379713371e+06},
    {+0.00000000000000000e+00, -5.70633918585143434e+01, +6.67932613126670458e+03},
    {+0.00000000000000000e+00, +0.00000000000000000e+00, +9.08192088387237417e-01},
};
static constexpr double kAr[5][3] = {
    {-1.96124944278866309e+06, +1.94163694836077630e+06, +1.96125142365061984e+04},
    {-2.52351924506418169e+08, +2.49825283835919440e+08, +1.17283609776914001e+09},
    {-3.94784176043574334e+04, -3.62546928411178640e+05, +6.48734166638722178e+06},
    {+0.00000000000000000e+00, -6.28318530717958623e+01, +7.38060580212308469e+03},
    {+0.00000000000000000e+00, +0.00000000000000000e+00, +1.00000000000000000e+00},
};

// ═══════════════════════════════════════════════════════════════
//  OPEN BASE + EXPLICIT BASE CURRENT (for the subsystem)
// ═══════════════════════════════════════════════════════════════
// n19 = kBo/kAo · n14  +  kBro/kAo · vr  +  kBz/kAo · ib
// WITHOUT `rpi`, `beta` or `Cb`: here the network is passive and
// the solution is EXACT superposition. The base stops being a fitted
// impedance and becomes the current the subsystem ALREADY computes
// per sample.
static constexpr int kGradoNumO = 2;
static constexpr int kGradoDenO = 2;
static constexpr int kKnobDegO = 2;
static constexpr int kGradoNumZ = 2;
static constexpr int kGradoNumRo = 2;
static constexpr double kBo[3][3] = {
    {+0.00000000000000000e+00, -2.01339929782222927e+05, +2.01339931795622222e+05},
    {+0.00000000000000000e+00, +0.00000000000000000e+00, +0.00000000000000000e+00},
    {+0.00000000000000000e+00, +0.00000000000000000e+00, +0.00000000000000000e+00},
};
static constexpr double kAo[3][3] = {
    {-3.94784176043574334e+04, +3.90836334283138567e+04, +2.03748117681619333e+05},
    {+0.00000000000000000e+00, -6.28318530717958623e+01, +1.01787603295778217e+03},
    {+0.00000000000000000e+00, +0.00000000000000000e+00, +1.00000000000000000e+00},
};
static constexpr double kBro[3][3] = {
    {-3.94784176043574334e+04, +2.40423563210536784e+05, +2.40818588599712302e+03},
    {+0.00000000000000000e+00, -6.28318530717958623e+01, +1.01787603295778217e+03},
    {+0.00000000000000000e+00, +0.00000000000000000e+00, +1.00000000000000000e+00},
};
static constexpr double kBz[3][3] = {
    {+2.01339929782222900e+10, -1.99326530484400673e+10, -2.01340133135554016e+08},
    {+0.00000000000000000e+00, +3.20442450666158907e+07, -3.55691126968727827e+08},
    {+0.00000000000000000e+00, +0.00000000000000000e+00, -5.10000000000000000e+05},
};

} // namespace level_v9ri
} // namespace nlsc
