// GENERATED BY harness/gen_coef_e234.py — DO NOT EDIT BY HAND.
//
// Coefficients of CASCADE stages 3 and 4, plus the rest points all
// four need. Fitted against the COMPLETE circuit's AC sweep
// (harness/spice/e234.cir) at the measurement's working point:
// drive=1.0, tone=0.5, lvl=0.0 (LEVEL at maximum).
//
// The coefficients depend on the KNOBS. This bank holds for THAT
//    point and nothing else: the cascade has no knob law here.
//
// Fit band: 20 Hz - 86400 Hz (internal-rate Nyquist).
// Fit residuals (whole band / 20 Hz-20 kHz only):
//   E3: orden 3, -151.2 / -151.2 dB   (n14/n7 — stage 3 (tone). LINEAR, measured at -156 dBc)
//   E4G1: orden 3, -175.1 / -174.9 dB   (n19/n14 — stage 4 input network (LEVEL pot + C8))
//   E4GS: orden 5, -108.0 / -107.7 dB   (n17/n19 NORMALISED at 8 kHz — only the residual charge step)
//   E4G2: orden 1, -174.6 / -174.5 dB   (out/n17 — stage 4 output (R14, C9, R15))
//   VRA: orden 2, -121.6 / -121.6 dB   (current n7 feeds the rail: (n9/n7)/R8, VR pinned, WITHOUT the pole)
//   VRB: orden 1, -39.3 / -39.3 dB   (current n14 feeds the rail: (n18/n14)/RLVL, VR pinned, WITHOUT the pole)
//   VRP: orden 2, -310.5 / -310.5 dB   (node VR impedance, 1/(Gtot + s*C11). Applied ONCE to the SUM)

#pragma once

namespace nlsc {
namespace e234_v9ri {

static constexpr double kFs = 192000.0;

// Complete circuit rest point (ngspice .op). The cascade works in
// DEVIATION from EACH node's rest, and none rests at VR.
//
// WHAT THE ENGINE READS FROM THIS FILE, AND WHAT IT DOES NOT.
// LIVE:   kFs · kQ_vr/kQ_n3/kQ_n19 · kG_* · kE3 · kE4G1 · kVRA/kVRB/kVRP
//         · kWS2*  (see nls_juegos.h, which is the only mapping)
// DEAD: kE4G2 · kE4GS · kE2C · kQ_n5 · kQ_n6 · kQ_n9 · kQ_n17.
//         The engine takes those filters from `fijos::` (s-domain,
//         nls_fijos_s*.h) and those rests from
//         nls_reposo_drive*.h. They are kept for the history and
//         because rail_ganancia.py reads its LEGADO block here.
//         => DO NOT cite them as evidence: they are not what runs.
static constexpr double kQ_vr = 4.495215;
static constexpr double kQ_n3 = 4.148169;
static constexpr double kQ_n6 = 3.578040;
static constexpr double kQ_n4 = 4.495125;
static constexpr double kQ_n5 = 4.495080;
static constexpr double kQ_n7 = 4.499768;
static constexpr double kQ_n9 = 4.499344;
static constexpr double kQ_n11 = 4.495215;
static constexpr double kQ_n14 = 4.499306;
static constexpr double kQ_n19 = 4.148169;
static constexpr double kQ_n17 = 3.578040;
static constexpr double kQ_out = 0.000000;

// Conductances feeding the VR rail from nodes the cascade ALREADY
// has. n7's and n14's are not here: they live inside kVRA/kVRB.
// kVRA and kVRB are CURRENTS (no pole): the `kVRP` pole applies
// ONCE to the SUM, the physical form and the only one that fits
// well. The why is in harness/gen_coef_e234.py.
static constexpr double kG_n3 = 1.960784313725e-06;
static constexpr double kG_n4 = 1.000000000000e-04;
static constexpr double kG_n11 = 2.127659574468e-04;
static constexpr double kG_n19 = 1.960784313725e-06;


// n14/n7 — stage 3 (tone). LINEAR, measured at -156 dBc
static constexpr int kE3_N = 2;
static constexpr double kE3[2][6] = {
    {+1.25054613863675879e-02, +2.50119045449430644e-02, +1.25064013572644007e-02, +1.00000000000000000e+00, +9.55991571096521553e-01, +0.00000000000000000e+00},
    {+1.00000000000000000e+00, -9.95869735205537787e-01, +0.00000000000000000e+00, +1.00000000000000000e+00, -1.96757075166991058e+00, +9.67686945929449371e-01},
};

// n19/n14 — stage 4 input network (LEVEL pot + C8)
static constexpr int kE4G1_N = 2;
static constexpr double kE4G1[2][6] = {
    {+9.86844340243291152e-01, +9.86583782803261755e-01, +0.00000000000000000e+00, +1.00000000000000000e+00, +9.97694734606481171e-01, +0.00000000000000000e+00},
    {+1.00000000000000000e+00, -1.99999995278488396e+00, +9.99999952784856094e-01, +1.00000000000000000e+00, -1.99982411696188356e+00, +9.99824122800572312e-01},
};

// n17/n19 NORMALISED at 8 kHz — only the residual charge step
static constexpr int kE4GS_N = 3;
static constexpr double kE4GS[3][6] = {
    {+9.99965125497729757e-01, -1.41789014020731230e+00, +5.02620164014276893e-01, +1.00000000000000000e+00, -7.08378094813491122e-01, +0.00000000000000000e+00},
    {+1.00000000000000000e+00, -1.97077335624840932e+00, +9.70986902372537597e-01, +1.00000000000000000e+00, -1.69489721800123494e+00, +6.99156241925380839e-01},
    {+1.00000000000000000e+00, +9.99813114964328453e-01, +0.00000000000000000e+00, +1.00000000000000000e+00, +1.43018669018004640e-02, -9.85180577075862485e-01},
};

// out/n17 — stage 4 output (R14, C9, R15)
static constexpr int kE4G2_N = 1;
static constexpr double kE4G2[1][6] = {
    {+9.95319406845414312e-01, -9.95319406814737850e-01, +0.00000000000000000e+00, +1.00000000000000000e+00, -9.99994816013984433e-01, +0.00000000000000000e+00},
};

// current n7 feeds the rail: (n9/n7)/R8, VR pinned, WITHOUT the pole
static constexpr int kVRA_N = 1;
static constexpr double kVRA[1][6] = {
    {+1.16719262849252082e-06, +5.28241661000788224e-09, -1.16191185417120257e-06, +1.00000000000000000e+00, -1.96757071262315475e+00, +9.67686908001124890e-01},
};

// current n14 feeds the rail: (n18/n14)/RLVL, VR pinned, WITHOUT the pole
static constexpr int kVRB_N = 1;
static constexpr double kVRB[1][6] = {
    {+9.86006327782055505e-06, -9.86001813129449753e-06, +0.00000000000000000e+00, +1.00000000000000000e+00, -9.99939588933897339e-01, +0.00000000000000000e+00},
};

// node VR impedance, 1/(Gtot + s*C11). Applied ONCE to the SUM
static constexpr int kVRP_N = 1;
static constexpr double kVRP[1][6] = {
    {+5.54058778979174063e-02, +1.42431562720223785e-03, -5.39815622707151693e-02, +1.00000000000000000e+00, -1.97422364051096544e+00, +9.74225399815991100e-01},
};

// E2C = IDENTITY: the ideal-opamp correction is MEASURED and
// OFF (buys 24,8 dB in small signal and LOSES 9,2 dB on real
// material, because the error depends on LEVEL).
static constexpr int kE2C_N = 1;
static constexpr double kE2C[1][6] = {
    {+1.0e+00, +0.0e+00, +0.0e+00, +1.0e+00, +0.0e+00, +0.0e+00},
};

// Q2 follower waveshaper, from `harness/spice/q2_curva.cir`.
// NOT extracted by driving the pedal INPUT: between the input and
// Q2 sit the diode clipping and the tone roll-off at 8 kHz, so that
// way `n19` stays under ±0,29 V while REAL material covers ±0,61 V
// (measured in the engine). Injected near Q2 to cover the true
// travel: extrapolating a polynomial does not degrade, it BLOWS UP
// (+41 dB). Input and output as DEVIATIONS from rest, not absolute.
// Chosen run: 0.80 V injection at 8 kHz.
// Travel covered by the fit: [-0.7946, +0.7943] V
// Fit auto-null: -104.6 dB
static constexpr double kWS2_UMIN = -7.946190413e-01;
static constexpr double kWS2_UMAX = +7.943405087e-01;
static constexpr int kWS2_N = 18;
// descending order, as np.polyval
static constexpr double kWS2[] = {
    -6.58243885258752610e-03,
    -1.71636483557835694e-02,
    +1.84611131010205681e-02,
    +4.60742003573590270e-02,
    -2.15442117011113987e-02,
    -5.09254996120820716e-02,
    +1.35322851866671104e-02,
    +2.98649814530244119e-02,
    -4.93858007251095962e-03,
    -9.97378675516555173e-03,
    +1.05171872609346323e-03,
    +1.89271874932676952e-03,
    -1.37347213948100702e-04,
    -1.35949418731982284e-04,
    -2.32139815279181725e-04,
    +1.19750418013569765e-03,
    +9.91738155424296997e-01,
    -4.89521794003472982e-08,
};

} // namespace e234_v9ri
} // namespace nlsc
