// GENERATED BY harness/gen_ley_tono.py — DO NOT EDIT BY HAND.
//
// THE TONE KNOB's LAW WITH THE dB SPREAD OUT — `ToneLaw::Even`.
//
// NOT the default. The shipped default is the real pot's G taper,
// which is FAITHFUL to the hardware; this law is offered as its own
// row of the `variant` selector, a product decision. Both come from
// the SAME circuit: what changes is which part of the pot's physical
// travel the knob position is given.
//
// WHY IT EXISTS. The OD-8's tone control concentrates its effect in
// the pot's last quarter: with the real pot's law, from knob 0,1 to 0,8
// the brightness moves −0,13 dB while the last tenth is worth +11 dB
// (2947 to 1 between the most and least effective tenth). It is not a
// model defect — four independent sources confirm it — it is the
// circuit, and the real G taper AGGRAVATES it.
//
// This table spreads the effect in dB PER TURN instead of resistance
// per turn, keeping the full range.
//
// The CIRCUIT does not change: this is the law between knob position
// and the pot's physical parameter, and the null against ngspice is
// identical. No null can see it — it runs on the parameter.
// Consequence, declared in the `.ttl`: on this row the knob position
// NO LONGER corresponds to the real pot's rotation.
//
// ONE table serves BOTH circuits: stage 3 does not depend on the
// variant (measured: under 0,0004 dB when `R13`/`R14` change), so there
// is no `_v9ri` twin of this file and there should not be one.
//
// brightness = dB(3-6 kHz) − dB(100-200 Hz) over stage 3's EXACT
// transfer. The reference band sits behind `C6`, where the tone does
// not act.
// Derived FROM `nls_tono_coef.h`: regenerating that bank invalidates
// this table. `make ley-tono` rebuilds it.
#pragma once

namespace nlsc {
namespace tone_law {

static constexpr int kN = 65;
static constexpr double kT[65] = {
    0.000000000, 0.001000000, 0.002000000, 0.003250000,
    0.004500000, 0.005750000, 0.007250000, 0.009000000,
    0.011000000, 0.013250000, 0.015750000, 0.019250000,
    0.023500000, 0.029000000, 0.036750000, 0.048750000,
    0.070500000, 0.147750000, 0.774250000, 0.814250000,
    0.841250000, 0.861500000, 0.877250000, 0.890250000,
    0.901000000, 0.910250000, 0.918250000, 0.925250000,
    0.931250000, 0.936750000, 0.941750000, 0.946000000,
    0.950000000, 0.953750000, 0.957250000, 0.960250000,
    0.963000000, 0.965750000, 0.968250000, 0.970500000,
    0.972500000, 0.974500000, 0.976250000, 0.978000000,
    0.979750000, 0.981250000, 0.982750000, 0.984000000,
    0.985500000, 0.986750000, 0.987750000, 0.989000000,
    0.990000000, 0.991000000, 0.992000000, 0.993000000,
    0.994000000, 0.994750000, 0.995500000, 0.996500000,
    0.997250000, 0.998000000, 0.998750000, 0.999500000,
    1.000000000,
};

} // namespace tone_law
} // namespace nlsc
