// GENERATED BY harness/gen_level_param.py — DO NOT EDIT BY HAND.
//
// The LEVEL network (E4G1 = n19/n14) as an EXPLICIT function of the
// knob. Replaces the fixed `kE4G1` of `nls_e234_coef*.h`, valid only
// at lvl=0: with it, turning the volume down cost up to +3,4 dB of
// ANMR.
//
// Q2's base enters as [rpi + (beta+1)*Ze(s)] || Cb: the follower
// describes the LOWS and the junction the HIGHS, and BOTH are needed.
// Fitted at four positions at once — two numbers for the whole
// travel, not a table. Valid because the pot sits BEFORE the base, so
// the load Q2 presents does not depend on the knob.
//
// FIT: rpi = 94.6448 kOhm, Cb = 2.8907 pF (beta = 416,4 from the netlist)
// The verification figure is NOT hand-written here: the run emits
// it, below. The one this line used to carry was from an EARLIER base
// model and sat 55 dB away from what the generator measured.
//
// THIS RUN:  R15 = 10000 Ohm (output load, after C9)  ·  R14 = 100 Ohm  ·  R13 = 10000 Ohm (Q2 emitter, both models)
//   worst signal residual n19/n14 :  -102.0 dB
//   worst rail -> n19 residual    :   -69.8 dB
#pragma once

namespace nlsc {
namespace level {

static constexpr double kScale = 6283.1853071795867;
static constexpr int kGradoNum = 3;
static constexpr int kGradoDen = 4;
static constexpr int kKnobDeg = 2;

// [power of s, highest to lowest][lvl^2 ... lvl^0]
static constexpr double kB[4][3] = {
    {+0.00000000000000000e+00, -1.18281089968131095e+08, +1.18281091150941998e+08},
    {+0.00000000000000000e+00, -1.83020274384758668e+05, +1.83020276214961428e+05},
    {+0.00000000000000000e+00, +0.00000000000000000e+00, +0.00000000000000000e+00},
    {+0.00000000000000000e+00, +0.00000000000000000e+00, +0.00000000000000000e+00},
};
static constexpr double kA[5][3] = {
    {-2.14833017786238517e+05, +2.12684687608376116e+05, +2.14833234767588601e+03},
    {-2.77292252973005027e+07, +2.74515911269602999e+07, +1.19744991049320117e+08},
    {-3.94784176043574334e+04, -5.04879931342820328e+03, +8.63370921276099631e+05},
    {+0.00000000000000000e+00, -6.28318530717958623e+01, +1.69110887798720228e+03},
    {+0.00000000000000000e+00, +0.00000000000000000e+00, +1.00000000000000000e+00},
};

// ═══════════════════════════════════════════════════════════════════
//  THE RAIL PATH: v(n19)/v(VR), ALSO a function of the knob.
// ═══════════════════════════════════════════════════════════════════
// This replaces `rail::kN19` of `nls_rail_n3.h`, which was ONE
// FIXED filter measured at lvl=0 — and the transfer changes 58x
// along the pot (0,0128 -> 0,742 at 1 kHz).
// Why it dominated the residual: the rail enters `n19` via `R12`,
// AFTER the pot, so its error does NOT attenuate with the knob. As
// the volume drops the signal falls 4,2x and the error stays => it
// rules.
// From the SAME matrix as `kB`/`kA` with the other right-hand
// side, and the SAME fitted Q2-base model: literally the
// superposition the cascade sums.
static constexpr int kGradoNumR = 3;
static constexpr int kGradoDenR = 4;
static constexpr int kKnobDegR = 2;

static constexpr double kBr[4][3] = {
    {-2.31923705819864906e+07, +1.41241536844297737e+08, +1.41473602255502087e+06},
    {-3.58863283107369934e+04, +1.81635935210966243e+05, +6.00160304034126108e+05},
    {+0.00000000000000000e+00, -5.71148654007241916e+01, +1.51273044119550491e+03},
    {+0.00000000000000000e+00, +0.00000000000000000e+00, +9.09011315255352059e-01},
};
static constexpr double kAr[5][3] = {
    {-2.14833017786238517e+05, +2.12684687608376116e+05, +2.14833234767588601e+03},
    {-2.77292252973005027e+07, +2.74515911269602999e+07, +1.19744991049320117e+08},
    {-3.94784176043574334e+04, -5.04879931342820328e+03, +8.63370921276099631e+05},
    {+0.00000000000000000e+00, -6.28318530717958623e+01, +1.69110887798720228e+03},
    {+0.00000000000000000e+00, +0.00000000000000000e+00, +1.00000000000000000e+00},
};

// ═══════════════════════════════════════════════════════════════
//  OPEN BASE + EXPLICIT BASE CURRENT (for the subsystem)
// ═══════════════════════════════════════════════════════════════
// n19 = kBo/kAo · n14  +  kBro/kAo · vr  +  kBz/kAo · ib
// WITHOUT `rpi`, `beta` or `Cb`: here the network is passive and
// the solution is EXACT superposition. The base stops being a fitted
// impedance and becomes the current the subsystem ALREADY computes
// per sample.
static constexpr int kGradoNumO = 2;
static constexpr int kGradoDenO = 2;
static constexpr int kKnobDegO = 2;
static constexpr int kGradoNumZ = 2;
static constexpr int kGradoNumRo = 2;
static constexpr double kBo[3][3] = {
    {+0.00000000000000000e+00, -2.01339929782222927e+05, +2.01339931795622222e+05},
    {+0.00000000000000000e+00, +0.00000000000000000e+00, +0.00000000000000000e+00},
    {+0.00000000000000000e+00, +0.00000000000000000e+00, +0.00000000000000000e+00},
};
static constexpr double kAo[3][3] = {
    {-3.94784176043574334e+04, +3.90836334283138567e+04, +2.03748117681619333e+05},
    {+0.00000000000000000e+00, -6.28318530717958623e+01, +1.01787603295778217e+03},
    {+0.00000000000000000e+00, +0.00000000000000000e+00, +1.00000000000000000e+00},
};
static constexpr double kBro[3][3] = {
    {-3.94784176043574334e+04, +2.40423563210536784e+05, +2.40818588599712302e+03},
    {+0.00000000000000000e+00, -6.28318530717958623e+01, +1.01787603295778217e+03},
    {+0.00000000000000000e+00, +0.00000000000000000e+00, +1.00000000000000000e+00},
};
static constexpr double kBz[3][3] = {
    {+2.01339929782222900e+10, -1.99326530484400673e+10, -2.01340133135554016e+08},
    {+0.00000000000000000e+00, +3.20442450666158907e+07, -3.55691126968727827e+08},
    {+0.00000000000000000e+00, +0.00000000000000000e+00, -5.10000000000000000e+05},
};

} // namespace level
} // namespace nlsc
