// GENERATED BY harness/gen_tono_param.py — DO NOT EDIT BY HAND.
//
// Stage 3 (TONE) as an EXPLICIT function of the knob, by exact
// algebra. Replaces the fixed `kE3` of `nls_e234_coef*.h`, valid only
// at tone=0,5: moving the knob to the ends with those cost up to
// +17,2 dB of ANMR.
//
// b(s) and a(s) with `s` in units of kScale, monic denominator.
// Each coefficient is a degree-2 polynomial in `tone` (Horner).
//
// VERIFIED:
//   · residual against ngspice: -120,2 to -132,8 dB at all 5 positions
//   · at tone=0,5 it reproduces the fitted banks EXACTLY:
//     -64,9 dB at 192 kHz and -77,0 dB at 384 kHz, same as theirs
//   · left-half-plane poles over the whole travel
#pragma once

namespace nlsc {
namespace tone {

static constexpr double kScale = 6283.1853071795867;
static constexpr int kGradoNum = 3;
static constexpr int kGradoDen = 4;

static constexpr int kKnobDeg = 2;

// [power of s, highest to lowest][t^2 ... t^0]
static constexpr double kB[4][3] = {
    {-7.97455187033592662e-05, +7.97455187033592662e-05, +2.20177381214971160e-04},
    {-1.59491037431898822e+04, +1.67465589302234730e+04, +1.75441726986499390e+02},
    {-2.51324623623180265e+01, +2.63890854802454342e+01, +5.77180788589165445e+02},
    {+0.00000000000000000e+00, +0.00000000000000000e+00, +9.09080947051778221e-01},
};
static constexpr double kA[5][3] = {
    {-7.35585757937967077e+00, +7.75112947689782050e+00, +8.52628198938115978e-02},
    {-2.20525452708957200e+04, +2.20526062830849878e+04, +2.43146389571143771e+02},
    {-1.75789399432083665e+04, +1.67814863072403168e+04, +1.78853041092934905e+03},
    {-2.76459851611921152e+01, +2.63893643366018971e+01, +6.37419468183096228e+02},
    {+0.00000000000000000e+00, +0.00000000000000000e+00, +1.00000000000000000e+00},
};

// ═══════════════════════════════════════════════════════════════
//  THE RAIL PATH: v(n14)/v(VR), ALSO a function of the knob.
// ═══════════════════════════════════════════════════════════════
// Replaces `rail::kN14` of `nls_rail_n3.h`, which was ONE
// FIXED filter measured at tone=0,5 — and the rail enters via `R8`
// BEFORE the tone network, so what it injects is filtered by the
// knob. Against ngspice, the frozen filter was wrong by −13,6 dB at
// tone=0 and −7,4 dB at tone=1.
// From the SAME matrix as `kB`/`kA` with the other right-hand
// side, opamp included: the superposition the cascade sums.
static constexpr int kGradoNumR = 4;
static constexpr int kGradoDenR = 4;
static constexpr int kKnobDegR = 2;

static constexpr double kBr[5][3] = {
    {-5.45813555311992771e-03, +5.73098776033448189e-03, +6.30411579170300741e-05},
    {-4.51595444477832005e-03, +4.54387900077281651e-03, +4.90853277348840154e-04},
    {-1.59491050464606292e+03, +1.67465602394159191e+03, +1.75443588386582867e+01},
    {-2.51324623623180265e+00, +2.63890854802454333e+00, +5.77180840228669183e+01},
    {+0.00000000000000000e+00, +0.00000000000000000e+00, +9.09080947051778276e-02},
};
static constexpr double kAr[5][3] = {
    {-7.35585757937967077e+00, +7.75112947689782050e+00, +8.52628198938115978e-02},
    {-2.20525452708957200e+04, +2.20526062830849878e+04, +2.43146389571143771e+02},
    {-1.75789399432083665e+04, +1.67814863072403168e+04, +1.78853041092934905e+03},
    {-2.76459851611921152e+01, +2.63893643366018971e+01, +6.37419468183096228e+02},
    {+0.00000000000000000e+00, +0.00000000000000000e+00, +1.00000000000000000e+00},
};

// ═══════════════════════════════════════════════════════════════
//  `VRA`: the CURRENT `n7` feeds the rail through `R8`.
// ═══════════════════════════════════════════════════════════════
// THIRD case of the same family. `VRA` is physically
// `(n9/n7)/R8`, and `n9` is loaded by the TONE NETWORK, so it
// DEPENDS on the knob — but the cascade held it as a bank constant
// (`J::VRA_A/B`), frozen at tone=0,5, while the tone itself was
// parametrised. Sibling of `VR -> n19` (frozen at lvl=0, +19,5 dB
// on fixing it) and of `VR -> n14` (above), in the OPPOSITE
// direction: not what the rail does to a node, but what the node
// feeds the rail.
//
// BOUNDED BEFORE WRITING IT, with the ORACLE's rail: `n7` goes
// from −56,3 to −74,0 dB at tone=0 (+17,7), and only +1,7 at
// tone=0,5 => all the error's tone dependence was this.
// From the SAME matrix, solving for `v9` instead of `v14`: no
// third copy of the equations.
static constexpr int kGradoNumV = 3;
static constexpr int kGradoDenV = 4;
static constexpr int kKnobDegV = 2;

static constexpr double kBv[4][3] = {
    {-5.32145952017390195e-04, +5.60741168542538667e-04, +6.16818147638823058e-06},
    {-1.59492717637460713e+00, +1.59492807926009794e+00, +1.75645732675157491e-02},
    {-2.51327137372065390e-03, +2.51327272459050564e-03, +5.77187172816626543e-02},
    {+0.00000000000000000e+00, +0.00000000000000000e+00, +9.09090494219479318e-05},
};
static constexpr double kAv[5][3] = {
    {-7.35585757937967077e+00, +7.75112947689782050e+00, +8.52628198938115978e-02},
    {-2.20525452708957200e+04, +2.20526062830849878e+04, +2.43146389571143771e+02},
    {-1.75789399432083665e+04, +1.67814863072403168e+04, +1.78853041092934905e+03},
    {-2.76459851611921152e+01, +2.63893643366018971e+01, +6.37419468183096228e+02},
    {+0.00000000000000000e+00, +0.00000000000000000e+00, +1.00000000000000000e+00},
};

} // namespace tone
} // namespace nlsc
