// GENERATED BY harness/gen_fijos_s.py — DO NOT EDIT BY HAND.
//
// The cascade's FIXED filters in `s`, to be discretised in
// `prepare()` at the REAL rate. With this the cascade stops being tied
// to the three tabulated rates and can run at any session rate.
//
// NOT a new fit: they come from INVERTING the bilinear over the SOS
// tables already committed and validated. The reason is that the inputs
// of `gen_coef_e234.py` (spice/ac_dcac3.dat, ac_dcac4.dat) are produced
// by no deck in the repo, so that generator cannot be re-run.
//
// The control is EXACT and the generator runs it: re-discretising at
// the source rate returns the starting table to machine precision.
//
// Convention: `s` in units of kScale = 2*pi*1000 (same as tone and
// level), coefficients from HIGHEST to lowest power, monic denominator.
//
// gen_fijos_s.py invocation:
//     --stage1 src/nls_stage1_coef.h
//     --e234   src/nls_e234_coef.h
//     --rail   src/nls_rail_n3.h
//     --railvr src/nls_rail_vr.h
//     --output src/nls_fijos_s.h
#pragma once

namespace nlsc {
namespace fijos {

static constexpr double kScale = 6283.1853071795858;

// stage1::H1 — stage 1 · input network
static constexpr int kH1_NB = 4;
static constexpr int kH1_NA = 4;
static constexpr double kH1_B[5][1] = {
    {+1.44846916463817481e-03},
    {+2.56372512700058223e+02},
    {+3.68722741851480077e+03},
    {+5.82011519545697951e+01},
    {+4.56733401162155501e-07},
};
static constexpr double kH1_A[5][1] = {
    {+6.11187181820789082e-03},
    {+2.57078122999672871e+02},
    {+3.70119827887569272e+03},
    {+1.27167808937581128e+02},
    {+1.00000000000000000e+00},
};

// stage1::HS — stage 1 · waveshaper network
static constexpr int kHS_NB = 6;
static constexpr int kHS_NA = 6;
static constexpr double kHS_B[7][1] = {
    {+1.66888934314892841e-08},
    {+8.04051503583892322e-05},
    {+1.49443461776499364e-01},
    {+1.78359271250123399e+01},
    {+9.09942882231249399e+01},
    {+6.47286666475930588e+01},
    {+1.00723103370984868e+00},
};
static constexpr double kHS_A[7][1] = {
    {+1.67443868026652671e-08},
    {+8.05104158051228228e-05},
    {+1.49455131417453313e-01},
    {+1.78358599575091858e+01},
    {+9.09914868796408314e+01},
    {+6.47177351678004271e+01},
    {+1.00000000000000000e+00},
};

// stage1::H2 — stage 1 · output network
static constexpr int kH2_NB = 4;
static constexpr int kH2_NA = 4;
static constexpr double kH2_B[5][1] = {
    {+1.38055086562933411e+02},
    {+7.47717793217332087e+02},
    {+5.99082016507847243e+02},
    {+6.28306463342604431e+01},
    {+1.99780321420340286e-06},
};
static constexpr double kH2_A[5][1] = {
    {+1.38055087577906903e+02},
    {+7.49915869019215052e+02},
    {+6.10982708227077978e+02},
    {+7.23655114294993638e+01},
    {+1.00000000000000000e+00},
};

// e234::E4GS — stage 4 · charge step n17/n19
static constexpr int kE4GS_NB = 6;
static constexpr int kE4GS_NA = 6;
static constexpr double kE4GS_B[7][1] = {
    {+1.34702475003554296e-06},
    {+1.67884072084721657e-03},
    {+5.09201211863001491e-01},
    {+4.20417164340816640e+01},
    {+3.00654554135076182e+02},
    {+5.30574247595349107e+02},
    {+1.00578812698613063e+00},
};
static constexpr double kE4GS_A[7][1] = {
    {+1.34795005511516306e-06},
    {+1.67914301832154428e-03},
    {+5.09225022836094166e-01},
    {+4.20417972619257867e+01},
    {+3.00654180385084885e+02},
    {+5.30572387896218288e+02},
    {+1.00000000000000000e+00},
};

// e234::E4G2 — stage 4 · output out/n17
static constexpr int kE4G2_NB = 2;
static constexpr int kE4G2_NA = 2;
static constexpr double kE4G2_B[3][1] = {
    {+5.14041899274911707e+00},
    {+6.28318534855222651e+02},
    {-7.42775429370497753e-09},
};
static constexpr double kE4G2_A[3][1] = {
    {+5.19182318253091779e+00},
    {+6.34609901416897173e+02},
    {+1.00000000000000000e+00},
};

// e234::E2C — opamp correction (OFF)
static constexpr int kE2C_NB = 2;
static constexpr int kE2C_NA = 2;
static constexpr double kE2C_B[3][1] = {
    {+6.69325385273529489e-05},
    {+1.63624617374468380e-02},
    {+1.00000000000000000e+00},
};
static constexpr double kE2C_A[3][1] = {
    {+6.69325385273529489e-05},
    {+1.63624617374468380e-02},
    {+1.00000000000000000e+00},
};

// rail::N3 — VR -> n3 (stage 1, via R2 510k)
static constexpr int kN3_NB = 6;
static constexpr int kN3_NA = 6;
static constexpr double kN3_B[7][1] = {
    {+1.21020899610728864e-05},
    {+1.97751281956644633e-02},
    {+2.47759392416907032e+00},
    {+3.03243578823988820e+01},
    {+1.02421047787834283e+02},
    {+6.44623434743493107e+01},
    {+9.08136812988528552e-01},
};
static constexpr double kN3_A[7][1] = {
    {+2.85585786853257285e-04},
    {+8.49549423097033696e+00},
    {+1.07928220545598697e+03},
    {+5.54880333506036004e+03},
    {+3.88240708112996617e+03},
    {+1.28591831948371464e+02},
    {+1.00000000000000000e+00},
};

// e234::VRA — current n7 feeds the rail
static constexpr int kVRA_NB = 2;
static constexpr int kVRA_NA = 2;
static constexpr double kVRA_B[3][1] = {
    {+1.40201907062354203e-14},
    {+7.23431115802924859e-05},
    {+1.00259353654030092e-05},
};
static constexpr double kVRA_A[3][1] = {
    {+1.00000000000000000e+00},
    {+1.00366027862752816e+00},
    {+1.10285539862215370e-01},
};

// e234::VRB — current n14 feeds the rail
static constexpr int kVRB_NB = 2;
static constexpr int kVRB_NA = 2;
static constexpr double kVRB_B[3][1] = {
    {+3.82743810778096984e-16},
    {+1.59154782267731496e-05},
    {-5.88409990068610033e-19},
};
static constexpr double kVRB_A[3][1] = {
    {+1.00000000000000000e+00},
    {+1.76661811639499788e+00},
    {+2.53302701483997233e-03},
};

// e234::VRC — current n19 feeds the rail
static constexpr int kVRC_NB = 2;
static constexpr int kVRC_NA = 2;
static constexpr double kVRC_B[3][1] = {
    {+1.19607842106419815e-05},
    {+5.05550491739169013e-06},
    {+4.96671964602191047e-09},
};
static constexpr double kVRC_A[3][1] = {
    {+1.00000000000000000e+00},
    {+1.76661811762567922e+00},
    {+2.53302701881972245e-03},
};

// e234::VRP — node VR impedance
static constexpr int kVRP_NB = 2;
static constexpr int kVRP_NA = 2;
static constexpr double kVRP_B[3][1] = {
    {+2.61410331517325587e-04},
    {+3.38608032546110937e+00},
    {+4.85925663148351061e-03},
};
static constexpr double kVRP_A[3][1] = {
    {+1.00000000000000000e+00},
    {+3.52602456743456418e-03},
    {+2.95246803072482935e-06},
};

} // namespace fijos
} // namespace nlsc
