// GENERATED BY harness/gen_reposo_drive.py — DO NOT EDIT BY HAND.
//
// Run with `.venv/bin/python`. Input: `spice/op_drive.txt`, produced by
// `ngspice -b spice/op_vs_drive.cir`.
//
// WHY — the corner that was missing, measured.
// The rest point is NOT fixed: the gain pot moves it. From drive 1,0 to
// drive 0,0: `n7` 6,09 mV, `n14` 5,71, `vr` and `n4` 1,90, `n3`/`n19` 1,38.
// The model shipped drive 1,0's, so with the drive closed and the signal
// weak that offset DOMINATES the residual: the 82 Hz / 0,1 V / drive 0
// corner read -38,7 dB while the rest of the sweep sat at -50/-63.
//
// It also fixes something carried from the start: stage 1's waveshaper
// was fitted centred on drive 0,5's rest (`Q_N3` = 3,32288) and was being
// evaluated at any drive. Here each waveshaper receives the DISPLACEMENT
// between today's rest and the one its curve was fitted at.
//
// Order 2 suffices (≤1,05 uV over the whole travel); 3 is used for 0,5 uV
// and three multiplies, evaluated ONCE in `prepare()`.

#pragma once

namespace nlsc {
namespace rest {

// Coefficients in DESCENDING order, as np.polyval.
// vr: from 4.493294 to 4.495215 V (+1.921 mV), fit ±0.49 uV
static constexpr double kvr[4] = {+6.68777785761912707e-06, -1.04263293295633807e-04, +2.01825121654599900e-03, +4.49329407547524884e+00};
// n3: from 4.146424 to 4.148169 V (+1.745 mV), fit ±0.49 uV
static constexpr double kn3[4] = {+9.35364321755430606e-06, -9.87105444828962784e-05, +1.83397481957653916e-03, +4.14642428336156676e+00};
// n6: from 3.576309 to 3.578040 V (+1.731 mV), fit ±0.52 uV
static constexpr double kn6[4] = {+3.66749110013902685e-06, -8.84992455079379345e-05, +1.81600246775248404e-03, +3.57630860662525896e+00};
// n4: from 4.493204 to 4.495125 V (+1.921 mV), fit ±0.49 uV
static constexpr double kn4[4] = {+6.68777785328272834e-06, -1.04263293289782950e-04, +2.01825121654483847e-03, +4.49320407547524781e+00};
// n7: from 4.493615 to 4.499768 V (+6.153 mV), fit ±0.45 uV
static constexpr double kn7[4] = {+1.26975321686687857e-05, -3.17385030472292818e-04, +6.45756534509319899e-03, +4.49361513363447873e+00};
// n14: from 4.493537 to 4.499306 V (+5.769 mV), fit ±0.51 uV
static constexpr double kn14[4] = {+1.24817973821046769e-05, -2.99271895169931333e-04, +6.05551962912185496e-03, +4.49353711970638070e+00};
// n19: from 4.146424 to 4.148169 V (+1.745 mV), fit ±0.49 uV
static constexpr double kn19[4] = {+9.35364321755430606e-06, -9.87105444828962784e-05, +1.83397481957653916e-03, +4.14642428336156676e+00};
// n17: from 3.576309 to 3.578040 V (+1.731 mV), fit ±0.52 uV
static constexpr double kn17[4] = {+3.66749110013902685e-06, -8.84992455079379345e-05, +1.81600246775248404e-03, +3.57630860662525896e+00};

// Rests each waveshaper was FITTED at. The difference against
// TODAY's rest is the displacement its input must receive.
static constexpr double kFit_n3 = 4.147318;
static constexpr double kFit_n6 = 3.577195;
static constexpr double kFit_n19 = 4.148169;
static constexpr double kFit_n17 = 3.578040;

inline double ev(const double (&c)[4], double g)
{
    double r = 0.0;
    for (int i = 0; i <= 3; ++i) r = r * g + c[i];
    return r;
}

// THE OUTPUT-CORRECTION SWITCH — is the waveshaper's OUTPUT corrected
// too, or only its INPUT? The output offset is a CONSTANT and the
// networks behind it block DC, so in steady state nothing changes — but
// starting with zeroed state it injects a TRANSIENT visible below 35 Hz.
// Kept as ONE constant so both can be measured with the same code:
//   -DNLSC_OUT_OFF=0.0  ->  only the input is corrected.
//
// AND THE GENERATOR EMITS IT, because it used to be HAND-WRITTEN in
// the generated file. Regenerating erased it and the build fell over with
// "kOffOutput is not a member of nlsc::reposo" — a generated file with
// manual edits is one nobody can regenerate.
#ifndef NLSC_OUT_OFF
#  define NLSC_OUT_OFF 1.0
#endif
static constexpr double kOffOutput = NLSC_OUT_OFF;

} // namespace rest
} // namespace nlsc
